name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test01
      id: test01
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test01
        setup-command: ''
        command: pytest autograder.py::TestPart1AdjustedKey
        timeout: 10
        max-score: 25
    - name: test02
      id: test02
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test02
        setup-command: ''
        command: pytest autograder.py::TestPart1And2Encryption
        timeout: 10
        max-score: 25
    - name: test03
      id: test03
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test03
        setup-command: ''
        command: pytest autograder.py::TestPart2Decryption
        timeout: 10
        max-score: 25
    - name: test04
      id: test04
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test04
        setup-command: ''
        command: pytest autograder.py::TestPart3MenuAndMain
        timeout: 10
        max-score: 25
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST01_RESULTS: "${{steps.test01.outputs.result}}"
        TEST02_RESULTS: "${{steps.test02.outputs.result}}"
        TEST03_RESULTS: "${{steps.test03.outputs.result}}"
        TEST04_RESULTS: "${{steps.test04.outputs.result}}"
      with:
        runners: test01,test02,test03,test04
